# Generated by Django 4.2.11 on 2024-03-04 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('vector_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Vector Id')),
                ('fio', models.CharField(max_length=255, verbose_name='FIO')),
                ('photo', models.TextField(verbose_name='Photo')),
            ],
            options={
                'verbose_name': 'Metadata',
                'verbose_name_plural': 'Metadata instances',
            },
        ),
    ]
