# Generated by Django 4.2.11 on 2024-04-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='firstname',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='firstName'),
        ),
    ]
