# Generated by Django 4.2.11 on 2024-03-04 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='fio',
        ),
        migrations.AddField(
            model_name='metadata',
            name='firstName',
            field=models.CharField(default='', max_length=255, verbose_name='firstName'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='patronymic',
            field=models.CharField(default='', max_length=255, verbose_name='patronymic'),
        ),
        migrations.AddField(
            model_name='metadata',
            name='surname',
            field=models.CharField(default='', max_length=255, verbose_name='surname'),
        ),
    ]
