# Generated by Django 4.2.11 on 2024-04-19 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_alter_metadata_patronymic_alter_metadata_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='iin',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='iin'),
        ),
    ]
