# Generated by Django 4.2.11 on 2024-05-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0006_alter_account_user_searchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='birthdate',
            field=models.DateField(blank=True, null=True, verbose_name='birthdate'),
        ),
    ]
